spring:
  application:
    name: 05_SB_Rest_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pkraygithub/Sb_Configuration_properties
server:
  port: 9099